[package]
name = "libsql-lua"
version = "0.1.0"
edition = "2021"

[lib]
name = "libsql"
path = "src/lib.rs"

[dependencies]
futures = "0.3.30"
libsql = "0.4.0"
mlua = { version = "0.9.9", features = ["luajit", "macros", "module"] }
